Asm4d_Proc proc_TEST;
Asm4d_Proc proc_ERRORHANDLER;
Asm4d_Proc proc_SystemWorkerProperties_2EonError;
Asm4d_Proc proc_SystemWorkerProperties_3Aconstructor;
Asm4d_Proc proc_SystemWorkerProperties_2EonTerminate;
Asm4d_Proc proc_SystemWorkerProperties_2EonDataError;
Asm4d_Proc proc_SystemWorkerProperties_2EonData;
Asm4d_Proc proc_SystemWorkerProperties_2EonResponse;
Asm4d_Proc proc_FileTransfer_2E__buildURL;
Asm4d_Proc proc_FileTransfer_2E__runWorker;
Asm4d_Proc proc_FileTransfer_2EsetmaxTime;
Asm4d_Proc proc_FileTransfer_2Eupload;
Asm4d_Proc proc_FileTransfer_2EsetCurlPrefix;
Asm4d_Proc proc_FileTransfer_2EsetAutoCreateLocalDirectory;
Asm4d_Proc proc_FileTransfer_2Edownload;
Asm4d_Proc proc_FileTransfer_2EsetAutoCreateRemoteDirectory;
Asm4d_Proc proc_FileTransfer_2EsetConnectTimeout;
Asm4d_Proc proc_FileTransfer_2EcreateDirectory;
Asm4d_Proc proc_FileTransfer_2EgetDirectoryListing;
Asm4d_Proc proc_FileTransfer_2Eversion;
Asm4d_Proc proc_FileTransfer_2Evalidate;
Asm4d_Proc proc_FileTransfer_3Aconstructor;

size_t Asm4d_handler_impl::sFunctionCount = 22;
Asm4d_ProcPtr Asm4d_handler_impl::sFunctions[] = {proc_TEST,proc_ERRORHANDLER,proc_SystemWorkerProperties_2EonError,proc_SystemWorkerProperties_3Aconstructor,proc_SystemWorkerProperties_2EonTerminate,proc_SystemWorkerProperties_2EonDataError,proc_SystemWorkerProperties_2EonData,proc_SystemWorkerProperties_2EonResponse,proc_FileTransfer_2E__buildURL,proc_FileTransfer_2E__runWorker,proc_FileTransfer_2EsetmaxTime,proc_FileTransfer_2Eupload,proc_FileTransfer_2EsetCurlPrefix,proc_FileTransfer_2EsetAutoCreateLocalDirectory,proc_FileTransfer_2Edownload,proc_FileTransfer_2EsetAutoCreateRemoteDirectory,proc_FileTransfer_2EsetConnectTimeout,proc_FileTransfer_2EcreateDirectory,proc_FileTransfer_2EgetDirectoryListing,proc_FileTransfer_2Eversion
	,proc_FileTransfer_2Evalidate,proc_FileTransfer_3Aconstructor};
